#Server
server:
  port: 8070

spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
      prefix: classpath:templates/
      suffix: .html
      mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/dailyproject
    username: root
    password: ekffu_qqo119
    driver-class-name: com.mysql.cj.jdbc.Driver
  
mybatis:
  # mapper 경로 지정
  mapper-locations: resources/query/**/*.xml
  configuration:
    map-underscore-to-camel-case: true